site_name: "redo: a recursive build system"
theme: readthedocs
docs_dir: Documentation
site_dir: website
strict: true
extra_javascript:
  - fetchcode.js

pages:
  - Introduction: index.md
  - Getting Started: GettingStarted.md
  - Cookbook:
    - Hello World: cookbook/hello.md
  - FAQ:
    - Basics: FAQBasics.md
    - Semantics: FAQSemantics.md
    - Interop with make: FAQInterop.md
    - Parallel Builds: FAQParallel.md
    - Implementation Details: FAQImpl.md
  - Contributing.md
  - Reference:
    - Manual Pages:
      - redo: redo.md
      - redo-ifchange: redo-ifchange.md
      - redo-ifcreate: redo-ifcreate.md
      - redo-always: redo-always.md
      - redo-stamp: redo-stamp.md
      - redo-sources: redo-sources.md
      - redo-targets: redo-targets.md
      - redo-ood: redo-ood.md
      - redo-whichdo: redo-whichdo.md
      - redo-log: redo-log.md
