site_name: "redo: a recursive build system"
theme:
  name: readthedocs
  hljs_languages:
    - python
    - r
    - shell
    - tex
docs_dir: docs
site_dir: docs.out
strict: true
repo_url: https://github.com/apenwarr/redo
edit_uri: edit/master/docs
extra_javascript:
  - fetchcode.js
extra_css:
  - extra_style.css
plugins:
  - exclude:
      glob:
        - cookbook/container/simple/*
        - cookbook/container/debdownload/*
        - cookbook/container/debootstrap/*
        - cookbook/container/debian/*
        - cookbook/container/libs/*
        - cookbook/container/*.fakeroot
        - cookbook/container/*.image
        - cookbook/container/*.initrd
        - cookbook/container/*.layer
        - cookbook/container/*.list
        - cookbook/c/out.*
        - "t/*"
        - "*.eps"
        - "*.gz"
        - "*.log"
        - "*.pdf"
        - "*.ps"
        - "*.tar"
        - "*.tmp"
        - "*.1"
      regex:
        - ".*~"

nav:
  - Introduction: index.md
  - Getting Started: GettingStarted.md
  - Contributing.md
  - Roadmap.md
  - Cookbook:
    - Hello World (hello.do, redo-ifchange): cookbook/hello/index.md
    - Text substitution (default.do, redo-always, redo-stamp): cookbook/defaults/index.md
    - R plots and LaTeX to pdf (side effects, multiple outputs): cookbook/latex/index.md
    - Docker and kvm containers (from scratch): cookbook/container/index.md
  - FAQ:
    - Basics: FAQBasics.md
    - Semantics: FAQSemantics.md
    - Interop with make: FAQInterop.md
    - Parallel Builds: FAQParallel.md
    - Implementation Details: FAQImpl.md
  - Reference Manual:
    - redo(1): redo.md
    - redo-ifchange(1): redo-ifchange.md
    - redo-ifcreate(1): redo-ifcreate.md
    - redo-always(1): redo-always.md
    - redo-stamp(1): redo-stamp.md
    - redo-sources(1): redo-sources.md
    - redo-targets(1): redo-targets.md
    - redo-ood(1): redo-ood.md
    - redo-whichdo(1): redo-whichdo.md
    - redo-log(1): redo-log.md
